# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#  - name: Tour
#    url: tour
#    weight: 10
  - name: Important Dates
    url: news
    weight: 10
  - name: Call for Papers
    url: cfp
    weight: 20    
  - name: Submission
    url: submission
    weight: 30    
  - name: Program
    url: program
    weight: 40
  - name: Keynotes
    url: speakers
    weight: 50
#  - name: Accepted Papers
#    url: publication
#    weight: 40
  - name: Organization
    url: people
    weight: 60
  - name: Contact
    url: contact
    weight: 70
  - name: FAIR2021
    url: fair2021
    weight: 80

